In [1]:
%run main.ipynb
%run hyperparameter_optimization.ipynb

0.10936965981495178
0.412136457171825
0.10936965981495178
0.412136457171825
Best parameters: {'fit_intercept': True, 'normalize': True}
 Best estimator: LinearRegression(normalize=True)
{'mean_fit_time': array([0.00154963, 0.00088449, 0.00096264, 0.00081697]), 'std_fit_time': array([6.69774604e-04, 1.77098784e-04, 2.50698178e-04, 3.48191051e-05]), 'mean_score_time': array([0.0003448 , 0.00029545, 0.0003705 , 0.00027075]), 'std_score_time': array([7.75436627e-05, 1.12670415e-04, 1.68504564e-04, 5.54495395e-05]), 'param_fit_intercept': masked_array(data=[True, True, False, False],
             mask=[False, False, False, False],
       fill_value='?',
            dtype=object), 'param_normalize': masked_array(data=[True, False, True, False],
             mask=[False, False, False, False],
       fill_value='?',
            dtype=object), 'params': [{'fit_intercept': True, 'normalize': True}, {'fit_intercept': True, 'normalize': False}, {'fit_intercept': False, 'normalize': True}, {'fit_in

/home/sudenur/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  warnings.warn(
/home/sudenur/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make

/home/sudenur/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: 
15 fits failed out of a total of 90.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "/home/sudenur/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/sudenur/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_forest.py", line 450, in fit
    trees = Parallel(
  File "/home/sudenur/anaconda3/lib/python3.8/site-packages/joblib/parallel.py", line 1043, in __call__
    if self.dispatch_one_batch(iterator):
  File "/home/sud

Best parameters: {'max_features': 4, 'n_estimators': 30}
 Best estimator: RandomForestRegressor(max_features=4, n_estimators=30, random_state=42)
keys:dict_keys(['mean_fit_time', 'std_fit_time', 'mean_score_time', 'std_score_time', 'param_max_features', 'param_n_estimators', 'param_bootstrap', 'params', 'split0_test_score', 'split1_test_score', 'split2_test_score', 'split3_test_score', 'split4_test_score', 'mean_test_score', 'std_test_score', 'rank_test_score']) 


 {'mean_fit_time': array([0.00400286, 0.01124554, 0.03766532, 0.00429339, 0.0120646 ,
       0.03188596, 0.00440521, 0.01261325, 0.046737  , 0.00355997,
       0.00571065, 0.01260715, 0.00494022, 0.01581836, 0.00674543,
       0.01801662, 0.00570979, 0.02070026]), 'std_fit_time': array([0.00021253, 0.00045776, 0.00573288, 0.00031703, 0.00050448,
       0.00041065, 0.00036044, 0.00045406, 0.0087859 , 0.00162734,
       0.00169522, 0.00163575, 0.00115806, 0.00256497, 0.00225351,
       0.00077569, 0.0018718 , 0.00320712]), 'me

/home/sudenur/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: 
35 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
35 fits failed with the following error:
Traceback (most recent call last):
  File "/home/sudenur/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/sudenur/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_forest.py", line 450, in fit
    trees = Parallel(
  File "/home/sudenur/anaconda3/lib/python3.8/site-packages/joblib/parallel.py", line 1043, in __call__
    if self.dispatch_one_batch(iterator):
  File "/home/sud

In [2]:
#import joblib # to save the results of models

### Better Evaluation Using Cross-Validation

Scikit-Learn’s **K-fold cross-validation** feature: randomly splits the training set into 10 distinct subsets called folds, <br>
then it trains and evaluates the Decision Tree model 10 times,<br>
picking a different fold for evaluation every time <br>
and training on the other 9 folds.<br> 
<br>
The result is an array containing the 10 evaluation scores:

In [3]:
from sklearn.model_selection import cross_val_score

**Evaluation for LinearRegregression model:**

In [4]:
lin_reg_scores = cross_val_score(tree_reg, titanic_clean, 
                         titanic_train_labels, scoring="neg_mean_squared_error", cv=10)

PS: Scikit-Learn’s cross-validation features expect a utility function (greater is better) rather than
a cost function (lower is better), so the scoring function is actually the opposite of the MSE.

In [5]:
lin_reg_scores_rms = np.sqrt(-lin_reg_scores)

In [6]:
lin_reg_scores_rms

array([0.49903535, 0.41670786, 0.5421875 , 0.50058566, 0.4719372 ,
       0.38049347, 0.45059004, 0.47107336, 0.44619661, 0.43615474])

In [7]:
# estimate of the performance of your model
print("mean:", lin_reg_scores.mean())
# how precise this estimate is
print("std:", lin_reg_scores.std())

# You would not have this information if you just used one validation set.

mean: -0.21489988828448564
std: 0.0405210205666955


In [8]:
print("%0.2f accuracy with a standard deviation of %0.2f"
      % (lin_reg_scores_rms.mean(), lin_reg_scores_rms.std()))

0.46 accuracy with a standard deviation of 0.04


In [9]:
#joblib.dump(lin_rms_scores, "lin_reg.pkl")
#my_model_loaded = joblib.load("lin_reg.pkl")
#my_model_loaded

Evaluation with the best parameters obtained from hyperparamater_optimization.ipynb:

In [10]:
best_lin_reg_grid_search = lin_reg_grid_search.best_estimator_

In [11]:
best_lin_reg_grid_search.predict(titanic_clean)

array([0.16015625, 0.8671875 , 0.66015625, 0.70703125, 0.140625  ,
       0.140625  , 0.16796875, 0.20703125, 0.6640625 , 0.8515625 ,
       0.70703125, 0.6328125 , 0.1640625 , 0.1640625 , 0.6796875 ,
       0.62890625, 0.20703125, 0.16015625, 0.6640625 , 0.796875  ,
       0.1640625 , 0.1484375 , 0.66796875, 0.1875    , 0.70703125,
       0.671875  , 0.2890625 , 0.49609375, 0.6484375 , 0.15234375,
       0.296875  , 0.98046875, 0.6484375 , 0.09375   , 0.38671875,
       0.1875    , 0.2890625 , 0.16015625, 0.6875    , 0.82421875,
       0.640625  , 0.67578125, 0.2890625 , 0.8828125 , 0.66015625,
       0.15234375, 0.1484375 , 0.6484375 , 0.30859375, 0.6875    ,
       0.22265625, 0.16015625, 0.85546875, 0.6796875 , 0.30078125,
       0.1875    , 0.671875  , 0.2890625 , 0.72265625, 0.2265625 ,
       0.30078125, 0.984375  , 0.22265625, 0.21484375, 0.31640625,
       0.30078125, 0.66015625, 0.1640625 , 0.67578125, 0.15234375,
       0.1484375 , 0.7265625 , 0.24609375, 0.30078125, 0.20703

In [12]:
best_lin_reg_grid_search_scores = cross_val_score(best_lin_reg_grid_search, titanic_clean, 
                         titanic_train_labels, scoring="neg_mean_squared_error", cv=10)

/home/sudenur/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  warnings.warn(
/home/sudenur/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make

In [13]:
best_lin_reg_grid_search_scores_rms = np.sqrt(-best_lin_reg_grid_search_scores)

In [14]:
best_lin_reg_grid_search_scores_rms

array([0.39864027, 0.38361078, 0.41871188, 0.3806152 , 0.41901505,
       0.39427333, 0.42906318, 0.42567232, 0.34805982, 0.40392333])

In [15]:
print("%0.2f accuracy with a standard deviation of %0.2f"
      % (best_lin_reg_grid_search_scores_rms.mean(), best_lin_reg_grid_search_scores_rms.std()))

0.40 accuracy with a standard deviation of 0.02


**Evaluation for DecisionTreeRegressor:**

In [16]:
tree_reg_scores = cross_val_score(tree_reg, titanic_clean, 
                         titanic_train_labels, scoring="neg_mean_squared_error", cv=10)

In [17]:
tree_reg_scores_rms = np.sqrt(-tree_reg_scores)

In [18]:
tree_reg_scores_rms

array([0.49903535, 0.41670786, 0.5421875 , 0.50058566, 0.4719372 ,
       0.38049347, 0.45059004, 0.47107336, 0.44619661, 0.43615474])

In [19]:
print("%0.2f accuracy with a standard deviation of %0.2f"
      % (tree_reg_scores_rms.mean(), tree_reg_scores_rms.std()))

0.46 accuracy with a standard deviation of 0.04


**Evaluation for RandomForestRegressor:**

In [20]:
forest_reg_scores = cross_val_score(tree_reg, titanic_clean, 
                         titanic_train_labels, scoring="neg_mean_squared_error", cv=10)

In [21]:
forest_reg_scores_rms = np.sqrt(-forest_reg_scores)

In [22]:
forest_reg_scores_rms

array([0.49903535, 0.41670786, 0.5421875 , 0.50058566, 0.4719372 ,
       0.38049347, 0.45059004, 0.47107336, 0.44619661, 0.43615474])

In [23]:
print("%0.2f accuracy with a standard deviation of %0.2f"
      % (forest_reg_scores_rms.mean(), forest_reg_scores_rms.std()))

0.46 accuracy with a standard deviation of 0.04


Evaluation with the best parameters obtained from hyperparamater_optimization.ipynb:

In [24]:
best_forest_reg_rand_search = forest_reg_rand_search.best_estimator_

In [25]:
best_forest_reg_rand_search.predict(titanic_clean)

array([0.        , 1.        , 0.875     , 1.        , 0.        ,
       0.01570513, 0.08333333, 0.33333333, 0.91666667, 0.75      ,
       0.75      , 0.95833333, 0.17361111, 0.08333333, 0.33333333,
       1.        , 0.16666667, 0.41909722, 0.29166667, 0.87037037,
       0.        , 0.29513889, 0.875     , 0.875     , 0.125     ,
       0.79166667, 0.        , 0.08333333, 1.        , 0.        ,
       0.16666667, 0.95833333, 0.7922551 , 0.29166667, 0.20833333,
       0.125     , 0.13979828, 0.02083333, 0.125     , 0.91666667,
       0.08333333, 0.25      , 0.04166667, 0.91666667, 0.83333333,
       0.        , 0.        , 0.7922551 , 0.25      , 0.125     ,
       0.25      , 0.29166667, 1.        , 0.95833333, 0.04166667,
       0.875     , 0.72916667, 0.04007937, 0.875     , 0.04166667,
       0.20833333, 0.95833333, 0.08333333, 0.25      , 0.06944444,
       1.        , 0.91666667, 0.3125    , 0.83333333, 0.125     ,
       0.        , 0.375     , 0.        , 0.04166667, 0.89722

In [26]:
best_forest_reg_rand_search_scores = cross_val_score(best_forest_reg_rand_search, titanic_clean, 
                         titanic_train_labels, scoring="neg_mean_squared_error", cv=10)

In [27]:
best_forest_reg_rand_search_scores_rms = np.sqrt(-best_forest_reg_rand_search_scores)
best_forest_reg_rand_search_scores_rms

array([0.4241263 , 0.38363993, 0.44114362, 0.38194328, 0.40094335,
       0.3505942 , 0.41721148, 0.43572322, 0.34843388, 0.36757544])

In [28]:
print("%0.2f accuracy with a standard deviation of %0.2f"
      % (best_forest_reg_rand_search_scores_rms.mean(), best_forest_reg_rand_search_scores_rms.std()))

0.40 accuracy with a standard deviation of 0.03


## The best performing model:

In [29]:
all_models = [lin_reg, tree_reg, forest_reg, 
              best_lin_reg_grid_search, best_forest_reg_rand_search]

In [30]:
all_scores_rms = [lin_reg_scores_rms, tree_reg_scores_rms, forest_reg_scores_rms, 
              best_lin_reg_grid_search_scores_rms, best_forest_reg_rand_search_scores_rms]

In [31]:
all_means = [format(score.mean(), ".2f") for score in all_scores_rms]
all_stds = [format(score.std(), ".2f") for score in all_scores_rms]

In [32]:
for model, score, std in zip(all_models, all_means, all_stds):
    print(model, score, "accuracy with a standard deviation of", std)


LinearRegression() 0.46 accuracy with a standard deviation of 0.04
DecisionTreeRegressor(random_state=42) 0.46 accuracy with a standard deviation of 0.04
RandomForestRegressor(random_state=42) 0.46 accuracy with a standard deviation of 0.04
LinearRegression(normalize=True) 0.40 accuracy with a standard deviation of 0.02
RandomForestRegressor(max_features=4, n_estimators=24, random_state=42) 0.40 accuracy with a standard deviation of 0.03


In [33]:
# get the best model according to the highest accuracy 
highest_accuracy_idx = all_means.index(max(all_means))
best_model = all_models[highest_accuracy_idx]
best_model

LinearRegression()