In [67]:
%run main.ipynb

In [68]:
#import joblib # to save the results of models

### Better Evaluation Using Cross-Validation

Scikit-Learn’s **K-fold cross-validation** feature: randomly splits the training set into 10 distinct subsets called folds, <br>
then it trains and evaluates the Decision Tree model 10 times,<br>
picking a different fold for evaluation every time <br>
and training on the other 9 folds.<br> 
<br>
The result is an array containing the 10 evaluation scores:

In [69]:
from sklearn.model_selection import cross_val_score

**Evaluation for LinearRegregression model:**

In [70]:
lin_reg_scores = cross_val_score(tree_reg, titanic_clean, 
                         titanic_train_labels, scoring="neg_mean_squared_error", cv=10)

PS: Scikit-Learn’s cross-validation features expect a utility function (greater is better) rather than
a cost function (lower is better), so the scoring function is actually the opposite of the MSE.

In [71]:
lin_rms_scores = np.sqrt(-lin_reg_scores)

In [72]:
lin_rms_scores

array([0.49903535, 0.41670786, 0.55245202, 0.52254944, 0.4719372 ,
       0.39498258, 0.4628902 , 0.44658504, 0.45861462, 0.50635783])

In [73]:
# estimate of the performance of your model
print("mean:", lin_reg_scores.mean())
# how precise this estimate is
print("std:", lin_reg_scores.std())

# You would not have this information if you just used one validation set.

mean: -0.22601099939559677
std: 0.04322186098344336


In [74]:
#joblib.dump(lin_rms_scores, "lin_reg.pkl")

In [75]:
#my_model_loaded = joblib.load("lin_reg.pkl")

In [76]:
#my_model_loaded

**Evaluation for DecisionTreeRegressor:**

In [77]:
tree_reg_scores = cross_val_score(tree_reg, titanic_clean, 
                         titanic_train_labels, scoring="neg_mean_squared_error", cv=10)

In [78]:
tree_rms_scores = np.sqrt(-tree_reg_scores)

In [79]:
tree_rms_scores

array([0.52082483, 0.41670786, 0.55245202, 0.52254944, 0.49517333,
       0.40895867, 0.4628902 , 0.44658504, 0.45554185, 0.48494823])

In [80]:
print("%0.2f accuracy with a standard deviation of %0.2f"
      % (tree_rms_scores.mean(), tree_rms_scores.std()))

0.48 accuracy with a standard deviation of 0.04


**Evaluation for RandomForestRegressor:**

In [81]:
forest_reg_scores = cross_val_score(tree_reg, titanic_clean, 
                         titanic_train_labels, scoring="neg_mean_squared_error", cv=10)

In [82]:
forest_rms_scores = np.sqrt(-forest_reg_scores)

In [83]:
forest_rms_scores

array([0.51004646, 0.40300061, 0.55245202, 0.52254944, 0.48369482,
       0.42247266, 0.45059004, 0.48285201, 0.47070513, 0.50635783])

In [84]:
print("%0.2f accuracy with a standard deviation of %0.2f"
      % (forest_rms_scores.mean(), forest_rms_scores.std()))

0.48 accuracy with a standard deviation of 0.04
